<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hl.Core\Hl.Core.csproj" />
    <ProjectReference Include="..\Hl.DataAccess\Hl.DataAccess.csproj" />
  </ItemGroup>

</Project>
